import "./globals.css";
import { Open_Sans } from "next/font/google";
import { Providers } from "./redux/provider";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import Script from "next/script";
import NextNProgressbar from "@/components/NextProgressbar";
export const dynamic = "force-dynamic";

const inter = Open_Sans({ subsets: ["latin"] });

export async function generateMetadata(): Promise<Metadata> {
  // const
  return {
    metadataBase: new URL(process.env.NEXT_PUBLIC_FRONT_END_URL as string),
    title: "Uncle Life",
    description: "Generated by Uncle Life",
    icons: {
      icon: "https://unclelife.co/favicon.ico",
    },
    openGraph: {
      type: "website",
      locale: "en_IE",
      url: "https://unclelife.co",
      siteName: "Uncle Life",
      images: ["https://unclelife.co/og2.jpg"],
    },
    twitter: {
      title: "Uncle Life",
      card: "summary_large_image",
      site: "@unclelife",
      creator: "@unclelife",
      images: ["https://unclelife.co/og2.jpg"],
    },
  };
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <NextNProgressbar />
        <Providers>{children}</Providers>
        <Toaster />
        <Script src="https://www.googletagmanager.com/gtag/js?id=G-C7BSJTQDVY" />
        <Script id="google-analytics">
          {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
 
          gtag('config', 'G-C7BSJTQDVY');
        `}
        </Script>
      </body>
    </html>
  );
}
