import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./redux/provider";
import NextNProgressbar from "@/components/NextProgressbar";
import { Toaster } from "@/components/ui/toaster";
import SupabaseProvider from "./hook/supabase-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Uncle Life",
  description: "Generated by Uncle Life",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SupabaseProvider>
          <NextNProgressbar />
          <Providers>{children}</Providers>
          <Toaster />
        </SupabaseProvider>
      </body>
    </html>
  );
}

export const dynamic = 'force-dynamic';
export const revalidate = 0;
