import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./redux/provider";
import NextNProgressbar from "@/components/NextProgressbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Uncle Life",
  description: "Generated by Uncle Life",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextNProgressbar />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
