import ToolsBar from "./components/toolsBar";

//layout
export const metadata = {
  title: "Uncle Life",
  description: "Generated by Uncle Life",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex">
      <ToolsBar />
      <div className="flex-grow p-4 w-full max-w-6xl mx-auto mt-14">
        {children}
      </div>
      <div className="text-black h-screen w-96 flex flex-col border-l px-3 ">
        asdas
      </div>
    </div>
  );
}
