import dynamic from "next/dynamic";
const LayerBar = dynamic(() => import("./components/layerBar"), { ssr: false });
const ToolsBar = dynamic(() => import("./components/toolsBar"), { ssr: false });
const CustomFormNavbar = dynamic(() => import("./components/navBar"), {
  ssr: false,
});

//layout
export const metadata = {
  title: "Uncle Life",
  description: "Generated by Uncle Life",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex min-h-screen h-fit bg-[#EFF1F3]">
      <CustomFormNavbar />
      <ToolsBar />
      <div className="flex-grow flex justify-center p-4 w-full max-w-6xl mx-auto mt-20">
        {children}
      </div>
      <LayerBar />
    </div>
  );
}
