import dynamic from "next/dynamic";
const LayerBar = dynamic(() => import("./components/layerBar"), { ssr: false });
const ToolsBar = dynamic(() => import("./components/toolsBar"), { ssr: false });

//layout
export const metadata = {
  title: "Uncle Life",
  description: "Generated by Uncle Life",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex">
      <ToolsBar />
      <div className="flex-grow flex justify-center p-4 w-full max-w-6xl mx-auto mt-14">
        {children}
      </div>
      <LayerBar />
    </div>
  );
}
