import Slidebars from "./components/Slidebar";

//layout
export const metadata = {
  title: "Uncle Life",
  description: "Generated by Uncle Life",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex">
      <Slidebars />
      <div className="flex-grow p-4 w-full max-w-6xl mx-auto">{children}</div>
    </div>
  );
}
